#!/bin/bash
set -e
PNGCRUSH_VERSION=1.7.92
cd /tmp
wget https://sourceforge.net/projects/pmt/files/pngcrush/old-versions/1.7/1.7.92/pngcrush-1.7.92.tar.gz
tar zxf pngcrush-$PNGCRUSH_VERSION.tar.gz
cd pngcrush-$PNGCRUSH_VERSION
make && cp -f pngcrush /usr/local/bin
cd /
rm -fr /tmp/pngcrush-$PNGCRUSH_VERSION
rm /tmp/pngcrush-$PNGCRUSH_VERSION.tar.gz
